### ISSUE TITLE
License/Attribution Question

### ISSUE THREAD

**Issue by retailcoder** [justcoding121/Windows-User-Action-Hook#1]
Hi,

I came across [this SO post](http://stackoverflow.com/q/11607133/1188513) and noticed the update pointing to this repository.

I haven't tried it yet but at first sight this looks like a very useful project and with your permission I'll use it in my own OSS project, [Rubberduck](https://github.com/rubberduck-vba/Rubberduck) - I'm not very familiar with licenses and their interactions, but my project is under GPL3; would it be ok to use your work there?

I'd like to also give proper credit/attribution, so if that's ok with you I'll add your project to our "About" window alongside Antlr4, LibGit2Sharp and the other OSS projects Rubberduck is using, and I'll add a link to this repository in the *attributions* section of my readme file.

Cheers!

**Comment by justcoding121** [comment]
I don't see why not.This project is under MIT license. However there are code snippets modified from other projects or code found in public domain of which I am not sure of license status. 

Code snippets used from other projects are as below and I have mentioned that in the inline comments. I think all of them are safe to be reused.
* [ClipboardHook.cs](https://github.com/justcoding121/Windows-User-Action-Hook/blob/master/EventHook/Hooks/ClipBoardHook.cs#L9) - [Source is from here](https://github.com/lemkepf/ClipHub/blob/master/ClipHub/ClipHub/Code/Helpers/ClipboardHelper.cs)
* [KeyboardHook.cs](https://github.com/justcoding121/Windows-User-Action-Hook/blob/master/EventHook/Hooks/KeyboardHook.cs#L10) - [Souce is from here](https://gist.github.com/Ciantic/471698)
* [PrintHook.cs](https://github.com/justcoding121/Windows-User-Action-Hook/blob/master/EventHook/Hooks/PrintQueueHook.cs) - [Souce is from here] (http://www.codeproject.com/Articles/51085/Monitor-jobs-in-a-printer-queue-NET)
* [ShellHook.cs](https://github.com/lemkepf/ClipHub/blob/master/ClipHub/ClipHub/Code/Helpers/ShellHook.cs) - [Source is from here] (https://github.com/lemkepf/ClipHub/blob/master/ClipHub/ClipHub/Code/Helpers/ShellHook.cs)

**Comment by retailcoder** [comment]
[Done!](https://github.com/rubberduck-vba/Rubberduck/blob/next/README.md#eventhook)

Your library is awesome, I was able to replace my buggy hooks in minutes!
