### ISSUE TITLE
It is needed "MouseMessages Enum" for wheelClick.

### ISSUE THREAD

**Issue by guhyeon** [justcoding121/Windows-User-Action-Hook#5]
It is needed "MouseMessages Enum" for wheelClick.

519 : WHEELCLICK_DOWN
520 : WHEELCLICK_UP

namespace EventHook.Hooks
{
    public enum MouseMessages
    {
        WM_MOUSEMOVE = 512,
        WM_LBUTTONDOWN = 513,
        WM_LBUTTONUP = 514,
        WM_RBUTTONDOWN = 516,
        WM_RBUTTONUP = 517,
        **WM_WHEELBUTTONDOWN = 519,
        WM_WHEELBUTTONUP = 520,**
        WM_MOUSEWHEEL = 522
    }
}

**Comment by justcoding121** [comment]
I will add this soon. Thanks

**Comment by justcoding121** [comment]
Fixed in latest release.
